
tree_full_md8_ml20_0 = {'feature': 405,
 'threshold': -1.03,
 'operator': '<=',
 'left': {'feature': 157,
          'threshold': -0.76,
          'operator': '<=',
          'left': {'feature': 460,
                   'threshold': -0.74,
                   'operator': '<=',
                   'left': {'id': 'leaf_1'},
                   'right': {'id': 'leaf_2'}},
          'right': {'feature': 435,
                    'threshold': -1.26,
                    'operator': '<=',
                    'left': {'feature': 274,
                             'threshold': -0.41,
                             'operator': '<=',
                             'left': {'id': 'leaf_3'},
                             'right': {'id': 'leaf_4'}},
                    'right': {'id': 'leaf_5'}}},
 'right': {'feature': 347,
           'threshold': -0.84,
           'operator': '<=',
           'left': {'feature': 317,
                    'threshold': -0.81,
                    'operator': '<=',
                    'left': {'feature': 466,
                             'threshold': -0.88,
                             'operator': '<=',
                             'left': {'feature': 429,
                                      'threshold': -0.79,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_6'},
                                      'right': {'id': 'leaf_7'}},
                             'right': {'id': 'leaf_8'}},
                    'right': {'id': 'leaf_9'}},
           'right': {'feature': 150,
                     'threshold': -0.42,
                     'operator': '<=',
                     'left': {'feature': 103,
                              'threshold': -0.17,
                              'operator': '<=',
                              'left': {'feature': 516,
                                       'threshold': -0.78,
                                       'operator': '<=',
                                       'left': {'id': 'leaf_10'},
                                       'right': {'id': 'leaf_11'}},
                              'right': {'id': 'leaf_12'}},
                     'right': {'id': 'leaf_13'}}}}



tree_full_md8_ml20_1 = {'feature': 350,
 'threshold': 0.39,
 'operator': '<=',
 'left': {'feature': 489,
          'threshold': -0.91,
          'operator': '<=',
          'left': {'feature': 381,
                   'threshold': -1.13,
                   'operator': '<=',
                   'left': {'feature': 464,
                            'threshold': -1.02,
                            'operator': '<=',
                            'left': {'id': 'leaf_1'},
                            'right': {'id': 'leaf_2'}},
                   'right': {'feature': 430,
                             'threshold': -0.84,
                             'operator': '<=',
                             'left': {'feature': 151,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_3'},
                                      'right': {'id': 'leaf_4'}},
                             'right': {'id': 'leaf_5'}}},
          'right': {'feature': 127,
                    'threshold': -0.52,
                    'operator': '<=',
                    'left': {'feature': 157,
                             'threshold': -0.75,
                             'operator': '<=',
                             'left': {'feature': 399,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'feature': 459,
                                               'threshold': -0.83,
                                               'operator': '<=',
                                               'left': {'id': 'leaf_6'},
                                               'right': {'id': 'leaf_7'}},
                                      'right': {'feature': 210,
                                                'threshold': -1.0,
                                                'operator': '<=',
                                                'left': {'id': 'leaf_8'},
                                                'right': {'id': 'leaf_9'}}},
                             'right': {'id': 'leaf_10'}},
                    'right': {'feature': 623,
                              'threshold': -0.48,
                              'operator': '<=',
                              'left': {'feature': 297,
                                       'threshold': -0.93,
                                       'operator': '<=',
                                       'left': {'id': 'leaf_11'},
                                       'right': {'id': 'leaf_12'}},
                              'right': {'id': 'leaf_13'}}}},
 'right': {'feature': 462,
           'threshold': -0.21,
           'operator': '<=',
           'left': {'feature': 460,
                    'threshold': -0.13,
                    'operator': '<=',
                    'left': {'feature': 292,
                             'threshold': -0.76,
                             'operator': '<=',
                             'left': {'id': 'leaf_14'},
                             'right': {'id': 'leaf_15'}},
                    'right': {'id': 'leaf_16'}},
           'right': {'feature': 206,
                     'threshold': -0.72,
                     'operator': '<=',
                     'left': {'feature': 328,
                              'threshold': -0.65,
                              'operator': '<=',
                              'left': {'id': 'leaf_17'},
                              'right': {'id': 'leaf_18'}},
                     'right': {'id': 'leaf_19'}}}}



tree_full_md8_ml20_2 = {'feature': 350,
 'threshold': 0.39,
 'operator': '<=',
 'left': {'feature': 489,
          'threshold': -0.91,
          'operator': '<=',
          'left': {'feature': 381,
                   'threshold': -1.1,
                   'operator': '<=',
                   'left': {'feature': 464,
                            'threshold': -1.05,
                            'operator': '<=',
                            'left': {'id': 'leaf_1'},
                            'right': {'id': 'leaf_2'}},
                   'right': {'feature': 430,
                             'threshold': -0.84,
                             'operator': '<=',
                             'left': {'feature': 151,
                                      'threshold': -0.5,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_3'},
                                      'right': {'id': 'leaf_4'}},
                             'right': {'id': 'leaf_5'}}},
          'right': {'feature': 127,
                    'threshold': -0.52,
                    'operator': '<=',
                    'left': {'feature': 157,
                             'threshold': -0.75,
                             'operator': '<=',
                             'left': {'feature': 399,
                                      'threshold': -0.5,
                                      'operator': '<=',
                                      'left': {'feature': 459,
                                               'threshold': -0.8,
                                               'operator': '<=',
                                               'left': {'id': 'leaf_6'},
                                               'right': {'id': 'leaf_7'}},
                                      'right': {'id': 'leaf_8'}},
                             'right': {'id': 'leaf_9'}},
                    'right': {'feature': 623,
                              'threshold': -0.5,
                              'operator': '<=',
                              'left': {'id': 'leaf_10'},
                              'right': {'id': 'leaf_11'}}}},
 'right': {'feature': 462,
           'threshold': -0.2,
           'operator': '<=',
           'left': {'feature': 405,
                    'threshold': -1.02,
                    'operator': '<=',
                    'left': {'feature': 157,
                             'threshold': -0.75,
                             'operator': '<=',
                             'left': {'feature': 460,
                                      'threshold': -0.7,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_12'},
                                      'right': {'id': 'leaf_13'}},
                             'right': {'id': 'leaf_14'}},
                    'right': {'id': 'leaf_15'}},
           'right': {'feature': 206,
                     'threshold': -0.75,
                     'operator': '<=',
                     'left': {'id': 'leaf_16'},
                     'right': {'id': 'leaf_17'}}}}



tree_full_md8_ml20_3 = {'feature': 405,
 'threshold': -1.03,
 'operator': '<=',
 'left': {'feature': 157,
          'threshold': -0.76,
          'operator': '<=',
          'left': {'feature': 460,
                   'threshold': -0.74,
                   'operator': '<=',
                   'left': {'feature': 415,
                            'threshold': -0.26,
                            'operator': '<=',
                            'left': {'id': 'leaf_1'},
                            'right': {'id': 'leaf_2'}},
                   'right': {'id': 'leaf_3'}},
          'right': {'feature': 435,
                    'threshold': -1.26,
                    'operator': '<=',
                    'left': {'feature': 274,
                             'threshold': -0.41,
                             'operator': '<=',
                             'left': {'feature': 352,
                                      'threshold': -0.85,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_4'},
                                      'right': {'id': 'leaf_5'}},
                             'right': {'id': 'leaf_6'}},
                    'right': {'feature': 402,
                              'threshold': -0.74,
                              'operator': '<=',
                              'left': {'id': 'leaf_7'},
                              'right': {'id': 'leaf_8'}}}},
 'right': {'feature': 347,
           'threshold': -0.84,
           'operator': '<=',
           'left': {'feature': 317,
                    'threshold': -0.81,
                    'operator': '<=',
                    'left': {'feature': 466,
                             'threshold': -0.88,
                             'operator': '<=',
                             'left': {'feature': 429,
                                      'threshold': -0.79,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_9'},
                                      'right': {'id': 'leaf_10'}},
                             'right': {'id': 'leaf_11'}},
                    'right': {'id': 'leaf_12'}},
           'right': {'feature': 150,
                     'threshold': -0.42,
                     'operator': '<=',
                     'left': {'feature': 103,
                              'threshold': -0.17,
                              'operator': '<=',
                              'left': {'feature': 516,
                                       'threshold': -0.78,
                                       'operator': '<=',
                                       'left': {'id': 'leaf_13'},
                                       'right': {'id': 'leaf_14'}},
                              'right': {'id': 'leaf_15'}},
                     'right': {'id': 'leaf_16'}}}}



tree_full_md8_ml20_4 = {'feature': 350,
 'threshold': 0.39,
 'operator': '<=',
 'left': {'feature': 489,
          'threshold': -0.91,
          'operator': '<=',
          'left': {'feature': 381,
                   'threshold': -1.13,
                   'operator': '<=',
                   'left': {'feature': 464,
                            'threshold': -1.02,
                            'operator': '<=',
                            'left': {'id': 'leaf_0'},
                            'right': {'id': 'leaf_5'}},
                   'right': {'feature': 430,
                             'threshold': -0.84,
                             'operator': '<=',
                             'left': {'feature': 151,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_7'},
                                      'right': {'id': 'leaf_3'}},
                             'right': {'id': 'leaf_9'}}},
          'right': {'feature': 127,
                    'threshold': -0.52,
                    'operator': '<=',
                    'left': {'feature': 157,
                             'threshold': -0.75,
                             'operator': '<=',
                             'left': {'feature': 399,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'feature': 459,
                                               'threshold': -0.83,
                                               'operator': '<=',
                                               'left': {'id': 'leaf_1'},
                                               'right': {'id': 'leaf_9'}},
                                      'right': {'feature': 210,
                                                'threshold': -1.0,
                                                'operator': '<=',
                                                'left': {'id': 'leaf_4'},
                                                'right': {'id': 'leaf_9'}}},
                             'right': {'id': 'leaf_8'}},
                    'right': {'feature': 623,
                              'threshold': -0.48,
                              'operator': '<=',
                              'left': {'feature': 297,
                                       'threshold': -0.93,
                                       'operator': '<=',
                                       'left': {'id': 'leaf_6'},
                                       'right': {'id': 'leaf_2'}},
                              'right': {'id': 'leaf_2'}}}},
 'right': {'feature': 462,
           'threshold': -0.21,
           'operator': '<=',
           'left': {'feature': 460,
                    'threshold': -0.13,
                    'operator': '<=',
                    'left': {'feature': 292,
                             'threshold': -0.76,
                             'operator': '<=',
                             'left': {'id': 'leaf_3'},
                             'right': {'id': 'leaf_5'}},
                    'right': {'id': 'leaf_8'}},
           'right': {'feature': 206,
                     'threshold': -0.72,
                     'operator': '<=',
                     'left': {'feature': 328,
                              'threshold': -0.65,
                              'operator': '<=',
                              'left': {'id': 'leaf_1'},
                              'right': {'id': 'leaf_8'}},
                     'right': {'id': 'leaf_8'}}}}



tree_full_md8_ml20_5 = {'feature': 350,
 'threshold': 0.39,
 'operator': '<=',
 'left': {'feature': 489,
          'threshold': -0.91,
          'operator': '<=',
          'left': {'feature': 381,
                   'threshold': -1.13,
                   'operator': '<=',
                   'left': {'feature': 464,
                            'threshold': -1.02,
                            'operator': '<=',
                            'left': {'id': 'leaf_1'},
                            'right': {'id': 'leaf_2'}},
                   'right': {'feature': 430,
                             'threshold': -0.84,
                             'operator': '<=',
                             'left': {'feature': 151,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_3'},
                                      'right': {'id': 'leaf_4'}},
                             'right': {'id': 'leaf_5'}}},
          'right': {'feature': 127,
                    'threshold': -0.52,
                    'operator': '<=',
                    'left': {'feature': 157,
                             'threshold': -0.75,
                             'operator': '<=',
                             'left': {'feature': 399,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'feature': 459,
                                               'threshold': -0.83,
                                               'operator': '<=',
                                               'left': {'id': 'leaf_6'},
                                               'right': {'id': 'leaf_7'}},
                                      'right': {'feature': 210,
                                                'threshold': -1.0,
                                                'operator': '<=',
                                                'left': {'id': 'leaf_8'},
                                                'right': {'id': 'leaf_9'}}},
                             'right': {'id': 'leaf_10'}},
                    'right': {'feature': 623,
                              'threshold': -0.48,
                              'operator': '<=',
                              'left': {'feature': 297,
                                       'threshold': -0.93,
                                       'operator': '<=',
                                       'left': {'id': 'leaf_11'},
                                       'right': {'id': 'leaf_12'}},
                              'right': {'id': 'leaf_13'}}}},
 'right': {'feature': 462,
           'threshold': -0.21,
           'operator': '<=',
           'left': {'feature': 460,
                    'threshold': -0.13,
                    'operator': '<=',
                    'left': {'feature': 292,
                             'threshold': -0.76,
                             'operator': '<=',
                             'left': {'id': 'leaf_14'},
                             'right': {'id': 'leaf_15'}},
                    'right': {'id': 'leaf_16'}},
           'right': {'feature': 206,
                     'threshold': -0.72,
                     'operator': '<=',
                     'left': {'feature': 328,
                              'threshold': -0.65,
                              'operator': '<=',
                              'left': {'id': 'leaf_17'},
                              'right': {'id': 'leaf_18'}},
                     'right': {'id': 'leaf_19'}}}}



tree_full_md8_ml20_6 = {'feature': 350,
 'threshold': 0.39,
 'operator': '<=',
 'left': {'feature': 489,
          'threshold': -0.91,
          'operator': '<=',
          'left': {'feature': 381,
                   'threshold': -1.13,
                   'operator': '<=',
                   'left': {'feature': 464,
                            'threshold': -1.02,
                            'operator': '<=',
                            'left': {'id': 'leaf_1'},
                            'right': {'id': 'leaf_2'}},
                   'right': {'feature': 430,
                             'threshold': -0.84,
                             'operator': '<=',
                             'left': {'feature': 151,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_3'},
                                      'right': {'id': 'leaf_4'}},
                             'right': {'id': 'leaf_5'}}},
          'right': {'feature': 127,
                    'threshold': -0.52,
                    'operator': '<=',
                    'left': {'feature': 157,
                             'threshold': -0.75,
                             'operator': '<=',
                             'left': {'feature': 399,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'feature': 459,
                                               'threshold': -0.83,
                                               'operator': '<=',
                                               'left': {'id': 'leaf_6'},
                                               'right': {'id': 'leaf_7'}},
                                      'right': {'feature': 210,
                                                'threshold': -1.0,
                                                'operator': '<=',
                                                'left': {'id': 'leaf_8'},
                                                'right': {'id': 'leaf_9'}}},
                             'right': {'id': 'leaf_10'}},
                    'right': {'feature': 623,
                              'threshold': -0.48,
                              'operator': '<=',
                              'left': {'feature': 297,
                                       'threshold': -0.93,
                                       'operator': '<=',
                                       'left': {'id': 'leaf_11'},
                                       'right': {'id': 'leaf_12'}},
                              'right': {'id': 'leaf_13'}}}},
 'right': {'feature': 462,
           'threshold': -0.21,
           'operator': '<=',
           'left': {'feature': 460,
                    'threshold': -0.13,
                    'operator': '<=',
                    'left': {'feature': 292,
                             'threshold': -0.76,
                             'operator': '<=',
                             'left': {'id': 'leaf_14'},
                             'right': {'id': 'leaf_15'}},
                    'right': {'id': 'leaf_16'}},
           'right': {'feature': 206,
                     'threshold': -0.72,
                     'operator': '<=',
                     'left': {'feature': 328,
                              'threshold': -0.65,
                              'operator': '<=',
                              'left': {'id': 'leaf_17'},
                              'right': {'id': 'leaf_18'}},
                     'right': {'id': 'leaf_19'}}}}



tree_full_md8_ml20_7 = {'feature': 350,
 'threshold': 0.39,
 'operator': '<=',
 'left': {'feature': 489,
          'threshold': -0.91,
          'operator': '<=',
          'left': {'feature': 381,
                   'threshold': -1.13,
                   'operator': '<=',
                   'left': {'feature': 464,
                            'threshold': -1.02,
                            'operator': '<=',
                            'left': {'id': 'leaf_0'},
                            'right': {'id': 'leaf_5'}},
                   'right': {'feature': 430,
                             'threshold': -0.84,
                             'operator': '<=',
                             'left': {'feature': 151,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_7'},
                                      'right': {'id': 'leaf_3'}},
                             'right': {'id': 'leaf_9'}}},
          'right': {'feature': 127,
                    'threshold': -0.52,
                    'operator': '<=',
                    'left': {'feature': 157,
                             'threshold': -0.75,
                             'operator': '<=',
                             'left': {'feature': 399,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'feature': 459,
                                               'threshold': -0.83,
                                               'operator': '<=',
                                               'left': {'id': 'leaf_7'},
                                               'right': {'id': 'leaf_9'}},
                                      'right': {'feature': 210,
                                                'threshold': -1.0,
                                                'operator': '<=',
                                                'left': {'id': 'leaf_4'},
                                                'right': {'id': 'leaf_9'}}},
                             'right': {'id': 'leaf_8'}},
                    'right': {'feature': 623,
                              'threshold': -0.48,
                              'operator': '<=',
                              'left': {'feature': 297,
                                       'threshold': -0.93,
                                       'operator': '<=',
                                       'left': {'id': 'leaf_6'},
                                       'right': {'id': 'leaf_2'}},
                              'right': {'id': 'leaf_2'}}}},
 'right': {'feature': 462,
           'threshold': -0.21,
           'operator': '<=',
           'left': {'feature': 460,
                    'threshold': -0.13,
                    'operator': '<=',
                    'left': {'feature': 292,
                             'threshold': -0.76,
                             'operator': '<=',
                             'left': {'id': 'leaf_3'},
                             'right': {'id': 'leaf_5'}},
                    'right': {'id': 'leaf_8'}},
           'right': {'feature': 206,
                     'threshold': -0.72,
                     'operator': '<=',
                     'left': {'feature': 328,
                              'threshold': -0.65,
                              'operator': '<=',
                              'left': {'id': 'leaf_1'},
                              'right': {'id': 'leaf_8'}},
                     'right': {'id': 'leaf_8'}}}}



tree_full_md8_ml20_8 = {'feature': 350,
 'threshold': 0.39,
 'operator': '<=',
 'left': {'feature': 489,
          'threshold': -0.91,
          'operator': '<=',
          'left': {'feature': 381,
                   'threshold': -1.13,
                   'operator': '<=',
                   'left': {'feature': 464,
                            'threshold': -1.02,
                            'operator': '<=',
                            'left': {'id': 'leaf_1'},
                            'right': {'id': 'leaf_2'}},
                   'right': {'feature': 430,
                             'threshold': -0.84,
                             'operator': '<=',
                             'left': {'feature': 151,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_7'},
                                      'right': {'id': 'leaf_3'}},
                             'right': {'id': 'leaf_9'}}},
          'right': {'feature': 127,
                    'threshold': -0.52,
                    'operator': '<=',
                    'left': {'feature': 157,
                             'threshold': -0.75,
                             'operator': '<=',
                             'left': {'feature': 399,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'feature': 459,
                                               'threshold': -0.83,
                                               'operator': '<=',
                                               'left': {'id': 'leaf_4'},
                                               'right': {'id': 'leaf_8'}},
                                      'right': {'feature': 210,
                                                'threshold': -1.0,
                                                'operator': '<=',
                                                'left': {'id': 'leaf_5'},
                                                'right': {'id': 'leaf_9'}}},
                             'right': {'id': 'leaf_6'}},
                    'right': {'feature': 623,
                              'threshold': -0.48,
                              'operator': '<=',
                              'left': {'feature': 297,
                                       'threshold': -0.93,
                                       'operator': '<=',
                                       'left': {'id': 'leaf_10'},
                                       'right': {'id': 'leaf_2'}},
                              'right': {'id': 'leaf_2'}}}},
 'right': {'feature': 462,
           'threshold': -0.21,
           'operator': '<=',
           'left': {'feature': 460,
                    'threshold': -0.13,
                    'operator': '<=',
                    'left': {'feature': 292,
                             'threshold': -0.76,
                             'operator': '<=',
                             'left': {'id': 'leaf_3'},
                             'right': {'id': 'leaf_8'}},
                    'right': {'id': 'leaf_6'}},
           'right': {'feature': 206,
                     'threshold': -0.72,
                     'operator': '<=',
                     'left': {'feature': 328,
                              'threshold': -0.65,
                              'operator': '<=',
                              'left': {'id': 'leaf_1'},
                              'right': {'id': 'leaf_7'}},
                     'right': {'id': 'leaf_6'}}}}



tree_full_md8_ml20_9 = {'feature': 350,
 'threshold': 0.39,
 'operator': '<=',
 'left': {'feature': 489,
          'threshold': -0.91,
          'operator': '<=',
          'left': {'feature': 381,
                   'threshold': -1.13,
                   'operator': '<=',
                   'left': {'feature': 464,
                            'threshold': -1.02,
                            'operator': '<=',
                            'left': {'id': 'leaf_1'},
                            'right': {'id': 'leaf_2'}},
                   'right': {'feature': 430,
                             'threshold': -0.84,
                             'operator': '<=',
                             'left': {'feature': 151,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'id': 'leaf_3'},
                                      'right': {'id': 'leaf_4'}},
                             'right': {'id': 'leaf_5'}}},
          'right': {'feature': 127,
                    'threshold': -0.52,
                    'operator': '<=',
                    'left': {'feature': 157,
                             'threshold': -0.75,
                             'operator': '<=',
                             'left': {'feature': 399,
                                      'threshold': -0.51,
                                      'operator': '<=',
                                      'left': {'feature': 459,
                                               'threshold': -0.83,
                                               'operator': '<=',
                                               'left': {'id': 'leaf_6'},
                                               'right': {'id': 'leaf_7'}},
                                      'right': {'id': 'leaf_8'}},
                             'right': {'id': 'leaf_9'}},
                    'right': {'feature': 623,
                              'threshold': -0.48,
                              'operator': '<=',
                              'left': {'feature': 297,
                                       'threshold': -0.93,
                                       'operator': '<=',
                                       'left': {'id': 'leaf_10'},
                                       'right': {'id': 'leaf_11'}},
                              'right': {'id': 'leaf_12'}}}},
 'right': {'feature': 462,
           'threshold': -0.21,
           'operator': '<=',
           'left': {'feature': 460,
                    'threshold': -0.13,
                    'operator': '<=',
                    'left': {'feature': 292,
                             'threshold': -0.76,
                             'operator': '<=',
                             'left': {'id': 'leaf_13'},
                             'right': {'id': 'leaf_14'}},
                    'right': {'id': 'leaf_15'}},
           'right': {'feature': 206,
                     'threshold': -0.72,
                     'operator': '<=',
                     'left': {'feature': 328,
                              'threshold': -0.65,
                              'operator': '<=',
                              'left': {'id': 'leaf_16'},
                              'right': {'id': 'leaf_17'}},
                     'right': {'id': 'leaf_18'}}}}


